Задача 1
--------
Дана порождающая матрица
$$
G = \left[\begin{array}{}
1 & 1 & 0 & 1 & 0 \\
0 & 1 & 1 & 0 & 1 \\
1 & 0 & 1 & 1 & 0 \\
\end{array}
\right]
$$
- Построить проверочную матрицу
- Определить все характеристики кода
- Построить таблицу для синдромного декодирования

## Все характеристики кода
$k = 3\ n = 5\ d_{min} = 1$
Количество ошибок, которое исправляет код $t = 0$

In [10]:
import numpy as np

In [93]:
rows = []
for i in range(32):
    binary = format(i, '05b')
    row = [int(bit) for bit in binary]
    rows.append(row)

e = np.array(rows)



In [94]:
e

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [70]:
rows = []
for i in range(8):
    binary = format(i, '03b')
    row = [int(bit) for bit in binary]
    rows.append(row)

m = np.array(rows)


## Проверочная матрица

In [112]:

G = np.array([
    [1,1,0,1,0],
    [0,1,1,0,1],
    [1,0,1,1,0]
])

H = np.array([
    [1,0,0,1,0],
    [0,1,1,1,0]
])

In [113]:
G@H.T%2

array([[0, 0],
       [0, 0],
       [0, 0]])

In [114]:
C = m @ G % 2
print(C)

[[0 0 0 0 0]
 [1 0 1 1 0]
 [0 1 1 0 1]
 [1 1 0 1 1]
 [1 1 0 1 0]
 [0 1 1 0 0]
 [1 0 1 1 1]
 [0 0 0 0 1]]


количество различных наборов 
$$\frac {2^n}{2^k} = \frac {2^5}{2^3}= 4$$

## Таблица синдромного декодирования

In [115]:
combinations = set()

for e_i in e:
    # Превращаем e_i в столбец (3,1) для broadcasting
    # e_col = e_i.reshape(-1, 1)  # или e_i[:, np.newaxis]
    
    # Теперь e_col (3,1) + C (3,2) = (3,2) - работает!
    summa = (e_i + C) % 2
    
    # Сортируем строки матрицы
    sorted_indices = np.lexsort(summa.T)
    sorted_matrix = summa[sorted_indices]
    
    # Преобразуем в неизменяемый тип для set
    matrix_tuple = tuple(tuple(int(x) for x in row) for row in sorted_matrix)
    combinations.add(matrix_tuple)


In [116]:
combinations

{((0, 0, 0, 0, 0),
  (0, 1, 1, 0, 0),
  (1, 1, 0, 1, 0),
  (1, 0, 1, 1, 0),
  (0, 0, 0, 0, 1),
  (0, 1, 1, 0, 1),
  (1, 1, 0, 1, 1),
  (1, 0, 1, 1, 1)),
 ((0, 1, 0, 0, 0),
  (0, 0, 1, 0, 0),
  (1, 0, 0, 1, 0),
  (1, 1, 1, 1, 0),
  (0, 1, 0, 0, 1),
  (0, 0, 1, 0, 1),
  (1, 0, 0, 1, 1),
  (1, 1, 1, 1, 1)),
 ((1, 0, 0, 0, 0),
  (1, 1, 1, 0, 0),
  (0, 1, 0, 1, 0),
  (0, 0, 1, 1, 0),
  (1, 0, 0, 0, 1),
  (1, 1, 1, 0, 1),
  (0, 1, 0, 1, 1),
  (0, 0, 1, 1, 1)),
 ((1, 1, 0, 0, 0),
  (1, 0, 1, 0, 0),
  (0, 0, 0, 1, 0),
  (0, 1, 1, 1, 0),
  (1, 1, 0, 0, 1),
  (1, 0, 1, 0, 1),
  (0, 0, 0, 1, 1),
  (0, 1, 1, 1, 1))}

In [117]:
print('Таблица синдромного декодирования\n')
for e_i in e:
    s = np.sum(((e_i @ H.T) % 2)) % 2
    print(f'{e_i}   {s}')

Таблица синдромного декодирования

[0 0 0 0 0]   0
[0 0 0 0 1]   0
[0 0 0 1 0]   0
[0 0 0 1 1]   0
[0 0 1 0 0]   1
[0 0 1 0 1]   1
[0 0 1 1 0]   1
[0 0 1 1 1]   1
[0 1 0 0 0]   1
[0 1 0 0 1]   1
[0 1 0 1 0]   1
[0 1 0 1 1]   1
[0 1 1 0 0]   0
[0 1 1 0 1]   0
[0 1 1 1 0]   0
[0 1 1 1 1]   0
[1 0 0 0 0]   1
[1 0 0 0 1]   1
[1 0 0 1 0]   1
[1 0 0 1 1]   1
[1 0 1 0 0]   0
[1 0 1 0 1]   0
[1 0 1 1 0]   0
[1 0 1 1 1]   0
[1 1 0 0 0]   0
[1 1 0 0 1]   0
[1 1 0 1 0]   0
[1 1 0 1 1]   0
[1 1 1 0 0]   1
[1 1 1 0 1]   1
[1 1 1 1 0]   1
[1 1 1 1 1]   1


# Задача 2
--------
Для двоичного кода Голея (23,12) определите минимальное расстояние и докажите, что код достигает границы Хэмминга.
$n = 23\ k = 12$ 
$d_{min} = 7$, тогда код способен исправлять
$$t= \frac{d_{min}-1}{2} = \frac{7-1}{2} = 3\ ошибки$$ 

докажем, что код достигает границы Хемминга
$$
M = 2^k = 2^{12}
$$
$$
M ≤ \frac{2^{23}}{\sum_{i=0}^3 \binom{23}{i}} = \frac{2^{23}}{1 + 23 + 253 + 1771} = \frac{2^{23}}{2048} = \frac{2^{23}}{2^{11}} = 2^{12}
$$
